Repository swoyam2609/Hacktober-2k22-NonTech, pull requests merged in 2022-10, with the labels that each got.

#4 Documentation for the repository
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: documentation, enhancement, hacktober22, hacktoberfest-accepted

#15 Future of AR/VR
  TECHNICAL BLOGS/future of AR_VR.txt
Labels: hacktober22, hacktoberfest-accepted, Technical Blogs

#17 CROSS-PLATFORM vs NATIVE App Dev
  TECHNICAL BLOGS/CROSS-PLATFORM vs NATIVE App Dev.txt
Labels: hacktober22, hacktoberfest-accepted, Technical Blogs

#19 created ADOBE XD vs FIGMA.txt
  ADOBE XD vs FIGMA.txt
Labels: hacktober22, hacktoberfest-accepted, Technical Blogs

#18 Blog on FUTURE OF AR/VR #13
  TECHNICAL BLOGS/Future With AR and VR
Labels: hacktober22, hacktoberfest-accepted, Technical Blogs

#20 Technical Blog in ADOBE XD vs FIGMA
  TECHNICAL BLOGS/Adobe XD vs Figma
Labels: hacktober22, hacktoberfest-accepted, Technical Blogs

#22 Hackathon Poster
  POSTERS/CODE HACKATHON.jpg
Labels: hacktober22, hacktoberfest-accepted, Designs

#23 Flutter Festival Poster
  POSTERS/Flutter Festival/Flutter Festival Poster 18x24in.png
Labels: hacktober22, hacktoberfest-accepted, Designs

#25 added tensor flow poster
  POSTERS/TensorFlow Week/Tensor Flow.png
Labels: hacktober22, hacktoberfest-accepted, Designs

#24 Designed a Poster for the Google event TENSORFLOW WEEK
  POSTERS/google-event-poster.png
Labels: hacktober22, hacktoberfest-accepted, Designs

#26 Created Microsoft Ignite 2022 poster
  POSTERS/Microsoft_Ignite_2022.png
Labels: hacktober22, hacktoberfest-accepted, Designs

#29 Added Blog on CryptoCurrency.
  TECHNICAL BLOGS/Cryptocurrency,12th sector of S&P .txt
Labels: hacktober22, hacktoberfest-accepted, Technical Blogs

#31 Add files via upload
  Flutter Festival canva link.txt
  Flutter Festival poster.png
Labels: hacktober22, hacktoberfest-accepted, Designs

#30 Added a technical blog on blockchain, please consider for merging
  TECHNICAL BLOGS/Future of Blockchain.txt
Labels: hacktober22, hacktoberfest-accepted, Technical Blogs

#33 Add files via upload
  Hackathon in you institute
  { hackathon }.png
Labels: hacktober22, hacktoberfest-accepted, Designs

#34 Added Kubernetes session poster.png
  POSTERS/Kubernetes Session Poster.png
Labels: hacktober22, hacktoberfest-accepted, Designs

#35 uploaded Mini Hackathon Poster
  POSTERS/MINI HACKATHON poster.png
Labels: hacktober22, hacktoberfest-accepted, Designs

#37 added poster for tensor flow week
  POSTERS/TensorFlow Week/tensor flow poster.jpg
Labels: hacktober22, hacktoberfest-accepted, Designs

#38 Assigned task completion TensorFlowWeek.png
  POSTERS/TensorFlow Week/TensorFlowWeek.png
Labels: hacktober22, hacktoberfest-accepted, Designs

#40 Added Microsoft ignite 2022 poster
  POSTERS/Microsoft Ignite.png
Labels: hacktober22, hacktoberfest-accepted, Designs

#42 Created and added a poster for 30 Days of Google Cloud.
  POSTERS/Akash_Parida/30DaysOfCloudPoster/30DaysOfCloudPoster-CanvaLink.txt
  POSTERS/Akash_Parida/30DaysOfCloudPoster/30_Days_Of_Cloud_Poster.png
Labels: hacktober22, hacktoberfest-accepted, Designs

#43 Created and added a poster for Flutter Festival event.
  POSTERS/Akash_Parida_2/Flutter Festival.png
  POSTERS/Akash_Parida_2/FlutterFestivalPoster_CanvaLink.txt
Labels: hacktober22, hacktoberfest-accepted, Designs

#41 Monolithic vs Microservices
  TECHNICAL BLOGS/Monolithic Architecture vs Microservices Architecture
Labels: hacktober22, hacktoberfest-accepted, Technical Blogs

#45 Article of cryptocurrency is added
  cryptocurrency.pdf
Labels: good first issue, hacktober22, hacktoberfest-accepted, Technical Blogs

#50 resolved issue number 8
  POSTERS/Abhinav khemani/poster hackfest.png
Labels: hacktober22, hacktoberfest-accepted, Designs

#49 Resolved issue #8: Added a poster of a mini hackathon (named MasterSt…
  POSTERS/Vanshika/MasterStack- Mini Hackathon.png
Labels: hacktober22, hacktoberfest-accepted, Designs

#48 Added a poster for hackathon 2022
  POSTERS/Shruti-sen2004/Hackathon Poster.jpg
Labels: hacktober22, hacktoberfest-accepted, Designs

#52 added a StarlinkProject.txt file
  TECHNICAL BLOGS/StarlinkProject.txt
Labels: hacktober22, hacktoberfest-accepted, Technical Blogs

#54 To add poster for kubernetes session to the posters folder
  POSTERS/Poster for kubernetes session.png
Labels: hacktober22, hacktoberfest-accepted, Designs

#56 added Technical Blogs
  POSTERS/prathamvbhat/Hackthon2022.jpg
  TECHNICAL BLOGS/graphic card
Labels: hacktober22, hacktoberfest-accepted, Technical Blogs

#60 Created Monolithic vs Microservices
  TECHNICAL BLOGS/Monolithic vs Microservices
Labels: hacktober22, hacktoberfest-accepted, Technical Blogs

#63 Added hacktober poster
  POSTERS/Hacktober poster.png
Labels: hacktober22, hacktoberfest-accepted, Designs

#65 Hacktoberfest poster by madhoolika
  POSTERS/MADHOOLIKA/Hactoberfest poster.png
  POSTERS/MADHOOLIKA/hacktoberfest
Labels: hacktober22, hacktoberfest-accepted, Designs

#64 Kotlin vs Java for Android Development
  TECHNICAL BLOGS/Kotlin vs Java for Android Development
Labels: hacktober22, hacktoberfest-accepted, Technical Blogs

#62 To add 30 days of cloud poster to the posters folder
  POSTERS/30 days of cloud poster.png
Labels: hacktober22, hacktoberfest-accepted, Designs

#61 Create nosql
  nosql
Labels: hacktober22, hacktoberfest-accepted, Technical Blogs
